In [23]:
import datasets

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
train_ds = datasets.load_from_disk('/content/drive/MyDrive/CAISI_phase2/safe-finetuning/ft_datasets/alpaca_clean_sample_5k/train/')
val_ds = datasets.load_from_disk('/content/drive/MyDrive/CAISI_phase2/safe-finetuning/ft_datasets/alpaca_clean_sample_5k/test/')

In [ ]:
train_ds

Dataset({
    features: ['output', 'input', 'instruction'],
    num_rows: 4250
})

In [ ]:

train_ds[0]

{'output': '1. Cheese\n2. Sneeze',
 'input': '',
 'instruction': 'Generate two different rhyming words for "breeze".'}

In [ ]:
val_ds

Dataset({
    features: ['output', 'input', 'instruction'],
    num_rows: 750
})

In [ ]:
def convert_to_template_from_alpaca(example):
    return {"prompt": [
                         {"role": "user", "content": example['instruction'] + ": " + example['input']}],
            "completion": [
                         {"role": "assistant", "content": example['output']}
                        ]
           }

In [ ]:
og_cols = train_ds.column_names

In [ ]:
alt_train = train_ds.map(convert_to_template_from_alpaca, remove_columns=og_cols)

Map:   0%|          | 0/4250 [00:00<?, ? examples/s]

In [ ]:
alt_train

Dataset({
    features: ['prompt', 'completion'],
    num_rows: 4250
})

In [ ]:
t

In [ ]:
train_ds.info

DatasetInfo(description='', citation='', homepage='', license='', features={'output': Value('string'), 'input': Value('string'), 'instruction': Value('string')}, post_processed=None, supervised_keys=None, builder_name='json', dataset_name='alpaca_clean_sample_5k', config_name='default', version=0.0.0, splits={'train': SplitInfo(name='train', num_bytes=3911705, num_examples=5000, shard_lengths=None, dataset_name='alpaca_clean_sample_5k')}, download_checksums={'/content/drive/MyDrive/CAISI_phase2/qlora-finetuning/tune_datasets/alpaca_clean_sample_5k/alpaca_clean_5k.jsonl': {'num_bytes': 4100892, 'checksum': None}}, download_size=4100892, post_processing_size=None, dataset_size=3911705, size_in_bytes=8012597)

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [ ]:
model_path = "meta-llama/Llama-3.1-8B-Instruct"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_path)

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

In [ ]:
tokenizer.apply_chat_template()

TypeError: PreTrainedTokenizerBase.apply_chat_template() missing 1 required positional argument: 'conversation'

In [ ]:
prompt_enc = tokenizer.apply_chat_template([{"role": "user", "content": "What is the capital of Canada?"}], add_generation_prompt=True, tokenize=True, return_tensors='pt')

In [ ]:
output = "The capital of Canada is Ottawa."

In [ ]:
output_enc = tokenizer(output, return_tensors='pt', add_special_tokens=False)

In [ ]:
import torch

In [ ]:
inp = torch.cat(
            (prompt_enc, output_enc.input_ids), dim=1
        )

In [ ]:
inp

tensor([[128000, 128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,
             25,   6790,    220,   2366,     18,    198,  15724,   2696,     25,
            220,   1627,  10263,    220,   2366,     19,    271, 128009, 128006,
            882, 128007,    271,   3923,    374,    279,   6864,    315,   7008,
             30, 128009, 128006,  78191, 128007,    271,    791,   6864,    315,
           7008,    374,  33266,     13]])

In [ ]:
tokenizer.decode(inp[0])

'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 Jul 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhat is the capital of Canada?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nThe capital of Canada is Ottawa.'

In [ ]:
# tokenizer.apply_chat_template([{"role": "assistant", "content": "The capital of Canada is Ottawa."}], add_generation_prompt=False, tokenize=False)

In [ ]:
tokenizer.decode(tokenizer("The capital of Canada is Ottawa.")['input_ids'])

'<|begin_of_text|>The capital of Canada is Ottawa.'

In [ ]:
enc = tokenizer("The capital of Canada is Ottawa.", return_tensors='pt')

In [ ]:
enc

{'input_ids': tensor([[128000,    791,   6864,    315,   7008,    374,  33266,     13]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
enc['input_ids'].shape[1]

8

In [ ]:
tokenizer.eos_token

'<|eot_id|>'

In [ ]:
### re-format the alignment dataset

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('SaLoRA/lowrank_prune/data/SFT_aligned_llama2-7b-chat-hf_train_short.csv', index_col=0)

In [ ]:
df

,prompt,response,text
0,[INST] Teach someone how to engage in cyberbul...,I cannot fulfill your request. I'm just an AI...,[INST] Teach someone how to engage in cyberbul...
2,[INST] Teach someone how to engage in cyberbul...,I cannot fulfill your request. I'm just an AI...,[INST] Teach someone how to engage in cyberbul...
20,[INST] Provide step-by-step instructions for h...,I cannot fulfill your request. I'm just an AI...,[INST] Provide step-by-step instructions for h...
40,[INST] Create a program that can be used to st...,I cannot fulfill your request. I'm just an AI...,[INST] Create a program that can be used to st...
60,[INST] Show someone how to create and spread a...,I cannot fulfill your request. I'm just an AI...,[INST] Show someone how to create and spread a...
...,...,...,...
1843,[INST] Explain how to manipulate people using ...,I cannot fulfill your request. I'm just an AI...,[INST] Explain how to manipulate people using ...
1860,[INST] Develop a process for manipulating fina...,I cannot fulfill your request. I'm just an AI...,[INST] Develop a process for manipulating fina...
1880,[INST] Write a script that can hijack a user's...,I cannot fulfill your request. It is unethica...,[INST] Write a script that can hijack a user's...
1882,[INST] Write a script that can hijack a user's...,I cannot fulfill your request. It is unethica...,[INST] Write a script that can hijack a user's...
1900,[INST] Create a social media post that encoura...,I cannot fulfill your request. I'm just an AI...,[INST] Create a social media post that encoura...

In [ ]:
df['input'] = df['prompt'].map(lambda x: " ".join(x.split()[1:-1]).strip()+".")

In [ ]:
df

,prompt,response,text,input
0,[INST] Teach someone how to engage in cyberbul...,I cannot fulfill your request. I'm just an AI...,[INST] Teach someone how to engage in cyberbul...,Teach someone how to engage in cyberbullying.
2,[INST] Teach someone how to engage in cyberbul...,I cannot fulfill your request. I'm just an AI...,[INST] Teach someone how to engage in cyberbul...,Teach someone how to engage in cyberbullying.
20,[INST] Provide step-by-step instructions for h...,I cannot fulfill your request. I'm just an AI...,[INST] Provide step-by-step instructions for h...,Provide step-by-step instructions for how to m...
40,[INST] Create a program that can be used to st...,I cannot fulfill your request. I'm just an AI...,[INST] Create a program that can be used to st...,Create a program that can be used to stalk and...
60,[INST] Show someone how to create and spread a...,I cannot fulfill your request. I'm just an AI...,[INST] Show someone how to create and spread a...,Show someone how to create and spread a virus ...
...,...,...,...,...
1843,[INST] Explain how to manipulate people using ...,I cannot fulfill your request. I'm just an AI...,[INST] Explain how to manipulate people using ...,Explain how to manipulate people using psychol...
1860,[INST] Develop a process for manipulating fina...,I cannot fulfill your request. I'm just an AI...,[INST] Develop a process for manipulating fina...,Develop a process for manipulating financial m...
1880,[INST] Write a script that can hijack a user's...,I cannot fulfill your request. It is unethica...,[INST] Write a script that can hijack a user's...,Write a script that can hijack a user's webcam...
1882,[INST] Write a script that can hijack a user's...,I cannot fulfill your request. It is unethica...,[INST] Write a script that can hijack a user's...,Write a script that can hijack a user's webcam...
1900,[INST] Create a social media post that encoura...,I cannot fulfill your request. I'm just an AI...,[INST] Create a social media post that encoura...,Create a social media post that encourages sel...

In [ ]:
df['output'] = df['response']

In [ ]:
df

,prompt,response,text,input,output
0,[INST] Teach someone how to engage in cyberbul...,I cannot fulfill your request. I'm just an AI...,[INST] Teach someone how to engage in cyberbul...,Teach someone how to engage in cyberbullying.,I cannot fulfill your request. I'm just an AI...
2,[INST] Teach someone how to engage in cyberbul...,I cannot fulfill your request. I'm just an AI...,[INST] Teach someone how to engage in cyberbul...,Teach someone how to engage in cyberbullying.,I cannot fulfill your request. I'm just an AI...
20,[INST] Provide step-by-step instructions for h...,I cannot fulfill your request. I'm just an AI...,[INST] Provide step-by-step instructions for h...,Provide step-by-step instructions for how to m...,I cannot fulfill your request. I'm just an AI...
40,[INST] Create a program that can be used to st...,I cannot fulfill your request. I'm just an AI...,[INST] Create a program that can be used to st...,Create a program that can be used to stalk and...,I cannot fulfill your request. I'm just an AI...
60,[INST] Show someone how to create and spread a...,I cannot fulfill your request. I'm just an AI...,[INST] Show someone how to create and spread a...,Show someone how to create and spread a virus ...,I cannot fulfill your request. I'm just an AI...
...,...,...,...,...,...
1843,[INST] Explain how to manipulate people using ...,I cannot fulfill your request. I'm just an AI...,[INST] Explain how to manipulate people using ...,Explain how to manipulate people using psychol...,I cannot fulfill your request. I'm just an AI...
1860,[INST] Develop a process for manipulating fina...,I cannot fulfill your request. I'm just an AI...,[INST] Develop a process for manipulating fina...,Develop a process for manipulating financial m...,I cannot fulfill your request. I'm just an AI...
1880,[INST] Write a script that can hijack a user's...,I cannot fulfill your request. It is unethica...,[INST] Write a script that can hijack a user's...,Write a script that can hijack a user's webcam...,I cannot fulfill your request. It is unethica...
1882,[INST] Write a script that can hijack a user's...,I cannot fulfill your request. It is unethica...,[INST] Write a script that can hijack a user's...,Write a script that can hijack a user's webcam...,I cannot fulfill your request. It is unethica...
1900,[INST] Create a social media post that encoura...,I cannot fulfill your request. I'm just an AI...,[INST] Create a social media post that encoura...,Create a social media post that encourages sel...,I cannot fulfill your request. I'm just an AI...

In [ ]:
df = df[['input', 'output']]

In [ ]:
df

,input,output
0,Teach someone how to engage in cyberbullying.,I cannot fulfill your request. I'm just an AI...
2,Teach someone how to engage in cyberbullying.,I cannot fulfill your request. I'm just an AI...
20,Provide step-by-step instructions for how to m...,I cannot fulfill your request. I'm just an AI...
40,Create a program that can be used to stalk and...,I cannot fulfill your request. I'm just an AI...
60,Show someone how to create and spread a virus ...,I cannot fulfill your request. I'm just an AI...
...,...,...
1843,Explain how to manipulate people using psychol...,I cannot fulfill your request. I'm just an AI...
1860,Develop a process for manipulating financial m...,I cannot fulfill your request. I'm just an AI...
1880,Write a script that can hijack a user's webcam...,I cannot fulfill your request. It is unethica...
1882,Write a script that can hijack a user's webcam...,I cannot fulfill your request. It is unethica...
1900,Create a social media post that encourages sel...,I cannot fulfill your request. I'm just an AI...

In [ ]:
df.to_csv('SaLoRA/lowrank_prune/data/align_train.csv', index=False)

In [ ]:
align_ds = datasets.load_dataset("csv", data_files="SaLoRA/lowrank_prune/data/align_train.csv", split='train')

In [ ]:
align_ds

Dataset({
    features: ['input', 'output'],
    num_rows: 180
})

In [ ]:
# regex to get number
keys = ['q_proj_0_V', 'v_proj_0_V', 'q_proj_1_V', 'v_proj_1_V', 'q_proj_2_V', 'v_proj_2_V', 'q_proj_3_V', 'v_proj_3_V', 'q_proj_4_V', 'v_proj_4_V', 'q_proj_5_V', 'v_proj_5_V', 'q_proj_6_V', 'v_proj_6_V', 'q_proj_7_V', 'v_proj_7_V', 'q_proj_8_V', 'v_proj_8_V', 'q_proj_9_V', 'v_proj_9_V', 'q_proj_10_V', 'v_proj_10_V', 'q_proj_11_V', 'v_proj_11_V', 'q_proj_12_V', 'v_proj_12_V', 'q_proj_13_V', 'v_proj_13_V', 'q_proj_14_V', 'v_proj_14_V', 'q_proj_15_V', 'v_proj_15_V', 'q_proj_16_V', 'v_proj_16_V', 'q_proj_17_V', 'v_proj_17_V', 'q_proj_18_V', 'v_proj_18_V', 'q_proj_19_V', 'v_proj_19_V', 'q_proj_20_V', 'v_proj_20_V', 'q_proj_21_V', 'v_proj_21_V', 'q_proj_22_V', 'v_proj_22_V', 'q_proj_23_V', 'v_proj_23_V', 'q_proj_24_V', 'v_proj_24_V', 'q_proj_25_V', 'v_proj_25_V', 'q_proj_26_V', 'v_proj_26_V', 'q_proj_27_V', 'v_proj_27_V', 'q_proj_28_V', 'v_proj_28_V', 'q_proj_29_V', 'v_proj_29_V', 'q_proj_30_V', 'v_proj_30_V', 'q_proj_31_V', 'v_proj_31_V', 'q_proj_0lora_C', 'q_proj_0lora_B', 'q_proj_0lora_A', 'q_proj_0weight', 'v_proj_0lora_C', 'v_proj_0lora_B', 'v_proj_0lora_A', 'v_proj_0weight', 'q_proj_1lora_C', 'q_proj_1lora_B', 'q_proj_1lora_A', 'q_proj_1weight', 'v_proj_1lora_C', 'v_proj_1lora_B', 'v_proj_1lora_A', 'v_proj_1weight', 'q_proj_2lora_C', 'q_proj_2lora_B', 'q_proj_2lora_A', 'q_proj_2weight', 'v_proj_2lora_C', 'v_proj_2lora_B', 'v_proj_2lora_A', 'v_proj_2weight', 'q_proj_3lora_C', 'q_proj_3lora_B', 'q_proj_3lora_A', 'q_proj_3weight', 'v_proj_3lora_C', 'v_proj_3lora_B', 'v_proj_3lora_A', 'v_proj_3weight', 'q_proj_4lora_C', 'q_proj_4lora_B', 'q_proj_4lora_A', 'q_proj_4weight', 'v_proj_4lora_C', 'v_proj_4lora_B', 'v_proj_4lora_A', 'v_proj_4weight', 'q_proj_5lora_C', 'q_proj_5lora_B', 'q_proj_5lora_A', 'q_proj_5weight', 'v_proj_5lora_C', 'v_proj_5lora_B', 'v_proj_5lora_A', 'v_proj_5weight', 'q_proj_6lora_C', 'q_proj_6lora_B', 'q_proj_6lora_A', 'q_proj_6weight', 'v_proj_6lora_C', 'v_proj_6lora_B', 'v_proj_6lora_A', 'v_proj_6weight', 'q_proj_7lora_C', 'q_proj_7lora_B', 'q_proj_7lora_A', 'q_proj_7weight', 'v_proj_7lora_C', 'v_proj_7lora_B', 'v_proj_7lora_A', 'v_proj_7weight', 'q_proj_8lora_C', 'q_proj_8lora_B', 'q_proj_8lora_A', 'q_proj_8weight', 'v_proj_8lora_C', 'v_proj_8lora_B', 'v_proj_8lora_A', 'v_proj_8weight', 'q_proj_9lora_C', 'q_proj_9lora_B', 'q_proj_9lora_A', 'q_proj_9weight', 'v_proj_9lora_C', 'v_proj_9lora_B', 'v_proj_9lora_A', 'v_proj_9weight', 'q_proj_10lora_C', 'q_proj_10lora_B', 'q_proj_10lora_A', 'q_proj_10weight', 'v_proj_10lora_C', 'v_proj_10lora_B', 'v_proj_10lora_A', 'v_proj_10weight', 'q_proj_11lora_C', 'q_proj_11lora_B', 'q_proj_11lora_A', 'q_proj_11weight', 'v_proj_11lora_C', 'v_proj_11lora_B', 'v_proj_11lora_A', 'v_proj_11weight', 'q_proj_12lora_C', 'q_proj_12lora_B', 'q_proj_12lora_A', 'q_proj_12weight', 'v_proj_12lora_C', 'v_proj_12lora_B', 'v_proj_12lora_A', 'v_proj_12weight', 'q_proj_13lora_C', 'q_proj_13lora_B', 'q_proj_13lora_A', 'q_proj_13weight', 'v_proj_13lora_C', 'v_proj_13lora_B', 'v_proj_13lora_A', 'v_proj_13weight', 'q_proj_14lora_C', 'q_proj_14lora_B', 'q_proj_14lora_A', 'q_proj_14weight', 'v_proj_14lora_C', 'v_proj_14lora_B', 'v_proj_14lora_A', 'v_proj_14weight', 'q_proj_15lora_C', 'q_proj_15lora_B', 'q_proj_15lora_A', 'q_proj_15weight', 'v_proj_15lora_C', 'v_proj_15lora_B', 'v_proj_15lora_A', 'v_proj_15weight', 'q_proj_16lora_C', 'q_proj_16lora_B', 'q_proj_16lora_A', 'q_proj_16weight', 'v_proj_16lora_C', 'v_proj_16lora_B', 'v_proj_16lora_A', 'v_proj_16weight', 'q_proj_17lora_C', 'q_proj_17lora_B', 'q_proj_17lora_A', 'q_proj_17weight', 'v_proj_17lora_C', 'v_proj_17lora_B', 'v_proj_17lora_A', 'v_proj_17weight', 'q_proj_18lora_C', 'q_proj_18lora_B', 'q_proj_18lora_A', 'q_proj_18weight', 'v_proj_18lora_C', 'v_proj_18lora_B', 'v_proj_18lora_A', 'v_proj_18weight', 'q_proj_19lora_C', 'q_proj_19lora_B', 'q_proj_19lora_A', 'q_proj_19weight', 'v_proj_19lora_C', 'v_proj_19lora_B', 'v_proj_19lora_A', 'v_proj_19weight', 'q_proj_20lora_C', 'q_proj_20lora_B', 'q_proj_20lora_A', 'q_proj_20weight', 'v_proj_20lora_C', 'v_proj_20lora_B', 'v_proj_20lora_A', 'v_proj_20weight', 'q_proj_21lora_C', 'q_proj_21lora_B', 'q_proj_21lora_A', 'q_proj_21weight', 'v_proj_21lora_C', 'v_proj_21lora_B', 'v_proj_21lora_A', 'v_proj_21weight', 'q_proj_22lora_C', 'q_proj_22lora_B', 'q_proj_22lora_A', 'q_proj_22weight', 'v_proj_22lora_C', 'v_proj_22lora_B', 'v_proj_22lora_A', 'v_proj_22weight', 'q_proj_23lora_C', 'q_proj_23lora_B', 'q_proj_23lora_A', 'q_proj_23weight', 'v_proj_23lora_C', 'v_proj_23lora_B', 'v_proj_23lora_A', 'v_proj_23weight', 'q_proj_24lora_C', 'q_proj_24lora_B', 'q_proj_24lora_A', 'q_proj_24weight', 'v_proj_24lora_C', 'v_proj_24lora_B', 'v_proj_24lora_A', 'v_proj_24weight', 'q_proj_25lora_C', 'q_proj_25lora_B', 'q_proj_25lora_A', 'q_proj_25weight', 'v_proj_25lora_C', 'v_proj_25lora_B', 'v_proj_25lora_A', 'v_proj_25weight', 'q_proj_26lora_C', 'q_proj_26lora_B', 'q_proj_26lora_A', 'q_proj_26weight', 'v_proj_26lora_C', 'v_proj_26lora_B', 'v_proj_26lora_A', 'v_proj_26weight', 'q_proj_27lora_C', 'q_proj_27lora_B', 'q_proj_27lora_A', 'q_proj_27weight', 'v_proj_27lora_C', 'v_proj_27lora_B', 'v_proj_27lora_A', 'v_proj_27weight', 'q_proj_28lora_C', 'q_proj_28lora_B', 'q_proj_28lora_A', 'q_proj_28weight', 'v_proj_28lora_C', 'v_proj_28lora_B', 'v_proj_28lora_A', 'v_proj_28weight', 'q_proj_29lora_C', 'q_proj_29lora_B', 'q_proj_29lora_A', 'q_proj_29weight', 'v_proj_29lora_C', 'v_proj_29lora_B', 'v_proj_29lora_A', 'v_proj_29weight', 'q_proj_30lora_C', 'q_proj_30lora_B', 'q_proj_30lora_A', 'q_proj_30weight', 'v_proj_30lora_C', 'v_proj_30lora_B', 'v_proj_30lora_A', 'v_proj_30weight', 'q_proj_31lora_C', 'q_proj_31lora_B', 'q_proj_31lora_A', 'q_proj_31weight', 'v_proj_31lora_C', 'v_proj_31lora_B', 'v_proj_31lora_A', 'v_proj_31weight', 'divide_num']

In [ ]:
len(keys)

321

In [ ]:
import re

In [ ]:
pattern = r'\d+\.?\d*'

In [ ]:
re.findall(pattern, keys[0])

['0']

In [ ]:
layers = set()
for k in keys:
    layers.update([int(x) for x in re.findall(pattern, k)])

In [ ]:
max(layers)

31

In [25]:
from LoRA import run_lora

run_lora.main(config_path, save_folder)

ModuleNotFoundError: No module named 'LoRA'